<?php

/**
 * Implements hook_install().
 */
function ai_provider_groq_install() {
  if (!module_load_install('ai_upgrade')) { return []; }
  ai_upgrade_module_install('ai_provider_groq');
}

/**
 * Implements hook_requirements().
 */
function ai_provider_groq_requirements($phase) {
  if (!module_load_install('ai_upgrade')) { return []; }
  return ai_upgrade_module_requirements($phase, 'ai_provider_groq');
}
